Add unit tests for Screenshot.cs
wubbl0rz/FrisyLUL pull request #1
Opened 2017-07-22 19:39 UTC by Schrotty

- Changed the visibilty of the screenshot class to public
- Add project for unit tests:
  - Includes first unit-tests for the screenshot class

2017-07-22 20:07 UTC, wubbl0rz requested changes

2017-07-22 20:07 UTC, wubbl0rz commented on FrisyLULTest/Test/TestScreenshot.cs
> +            Screenshot.TakeScreenshot(_invalidProcess).ToBase64(ImageFormat.Png); //see you in /dev/null
der string sollte empty sein wenn screenshot empty ist. falls das nicht so ist würde ich sagen das is ein bug ^^

2017-07-22 20:07 UTC, wubbl0rz commented on FrisyLULTest/Test/TestScreenshot.cs
> +            Assert.IsTrue(img.Size.Width == 1 && img.Size.Height == 1);
save bei empty screenshot sollte am besten gar nix saven.  wenn paar tests fehlschlagen is gut dann kann ich das morgen im stream fixen

2017-07-22 20:07 UTC, wubbl0rz commented on FrisyLULTest/Test/TestScreenshot.cs
> +        private String _validProcess = "firefox";
findest du bei den 3 prozessen evtl. irgendwas das default auf jedem windows valid, minimiert oder invalid ist ?

2017-07-22 20:08 UTC, wubbl0rz commented
bitte noch rebasen auf master :D

2017-07-22 21:14 UTC, Schrotty commented on FrisyLULTest/Test/TestScreenshot.cs
> +            Screenshot.TakeScreenshot(_invalidProcess).ToBase64(ImageFormat.Png); //see you in /dev/null
Scheint nen Bug zu sein. Ich vermute mal da die Bitmap nie null ist findet die ToBase64String() immer noch was was sie verarbeiten kann.

2017-07-22 21:15 UTC, Schrotty commented on FrisyLULTest/Test/TestScreenshot.cs
> +            Assert.IsTrue(img.Size.Width == 1 && img.Size.Height == 1);
Ok, der Test erwartet jetzt das eine FileNotFoundException geworfen wird. Sprich: Save() mit nem leeren Screenshot macht nichts.

2017-07-22 21:21 UTC, Schrotty commented on FrisyLULTest/Test/TestScreenshot.cs
> +        private String _validProcess = "firefox";
Hab versucht den Windows Explorer zu nehmen, nur wird der, und auch Notepad von TakeScreenshot() nicht richtig erkannt und TakeScreenshot() liefert jedesmal einen leeren Screenshot zurück. Wenn ich Firefox als validen Prozess nutze klappt es.
Keine Ahnung woran es da hapert. Zumal es im Stream ja funktioniert hat.

2017-07-23 09:50 UTC, wubbl0rz approved these changes

2017-07-23 11:33 UTC, Schrotty commented
Rebase ist erledigt

2017-07-24 08:49 UTC, merged